FROM node:24.9.0-slim as ui-deps

WORKDIR /app

COPY frontend/package.json frontend/yarn.lock ./
COPY frontend/packages/ ./packages

RUN yarn install --frozen-lockfile

FROM node:24.9.0-slim as ui-build

WORKDIR /app

COPY frontend .
RUN find . -type d -name '__tests__' -exec rm -rf {} + || true
RUN find . -type f \( -name '*.test.tsx' -o -name '*.test.ts' -o -name '*.spec.tsx' -o -name '*.spec.ts' \) -delete
COPY --from=ui-deps /app/node_modules ./node_modules

ENV API_SERVICE=http://localhost:8080/api/

RUN yarn build && yarn install --production --ignore-scripts --prefer-offline

FROM node:24.9.0-slim as publish-ui

# Install CA certificates for HTTPS requests
RUN apt-get update && \
    apt-get install -y ca-certificates && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app
ENV NODE_ENV production

COPY --from=ui-build /app/next.config.js ./
COPY --from=ui-build /app/public ./public
COPY --from=ui-build /app/.next ./.next
COPY --from=ui-build /app/node_modules ./node_modules
COPY --from=ui-build /app/package.json ./package.json

EXPOSE 3000

CMD ["yarn", "start"]
