// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/annymsMthd/industry-tool/internal/updaters (interfaces: MarketPricesRepository,MarketPricesEsiClient)

// Package updaters_test is a generated GoMock package.
package updaters_test

import (
	context "context"
	reflect "reflect"
	time "time"

	client "github.com/annymsMthd/industry-tool/internal/client"
	models "github.com/annymsMthd/industry-tool/internal/models"
	gomock "github.com/golang/mock/gomock"
)

// MockMarketPricesRepository is a mock of MarketPricesRepository interface.
type MockMarketPricesRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMarketPricesRepositoryMockRecorder
}

// MockMarketPricesRepositoryMockRecorder is the mock recorder for MockMarketPricesRepository.
type MockMarketPricesRepositoryMockRecorder struct {
	mock *MockMarketPricesRepository
}

// NewMockMarketPricesRepository creates a new mock instance.
func NewMockMarketPricesRepository(ctrl *gomock.Controller) *MockMarketPricesRepository {
	mock := &MockMarketPricesRepository{ctrl: ctrl}
	mock.recorder = &MockMarketPricesRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMarketPricesRepository) EXPECT() *MockMarketPricesRepositoryMockRecorder {
	return m.recorder
}

// DeleteAllForRegion mocks base method.
func (m *MockMarketPricesRepository) DeleteAllForRegion(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAllForRegion", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAllForRegion indicates an expected call of DeleteAllForRegion.
func (mr *MockMarketPricesRepositoryMockRecorder) DeleteAllForRegion(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAllForRegion", reflect.TypeOf((*MockMarketPricesRepository)(nil).DeleteAllForRegion), arg0, arg1)
}

// GetLastUpdateTime mocks base method.
func (m *MockMarketPricesRepository) GetLastUpdateTime(arg0 context.Context, arg1 int64) (*time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastUpdateTime", arg0, arg1)
	ret0, _ := ret[0].(*time.Time)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLastUpdateTime indicates an expected call of GetLastUpdateTime.
func (mr *MockMarketPricesRepositoryMockRecorder) GetLastUpdateTime(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastUpdateTime", reflect.TypeOf((*MockMarketPricesRepository)(nil).GetLastUpdateTime), arg0, arg1)
}

// UpsertPrices mocks base method.
func (m *MockMarketPricesRepository) UpsertPrices(arg0 context.Context, arg1 []models.MarketPrice) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertPrices", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertPrices indicates an expected call of UpsertPrices.
func (mr *MockMarketPricesRepositoryMockRecorder) UpsertPrices(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertPrices", reflect.TypeOf((*MockMarketPricesRepository)(nil).UpsertPrices), arg0, arg1)
}

// MockMarketPricesEsiClient is a mock of MarketPricesEsiClient interface.
type MockMarketPricesEsiClient struct {
	ctrl     *gomock.Controller
	recorder *MockMarketPricesEsiClientMockRecorder
}

// MockMarketPricesEsiClientMockRecorder is the mock recorder for MockMarketPricesEsiClient.
type MockMarketPricesEsiClientMockRecorder struct {
	mock *MockMarketPricesEsiClient
}

// NewMockMarketPricesEsiClient creates a new mock instance.
func NewMockMarketPricesEsiClient(ctrl *gomock.Controller) *MockMarketPricesEsiClient {
	mock := &MockMarketPricesEsiClient{ctrl: ctrl}
	mock.recorder = &MockMarketPricesEsiClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMarketPricesEsiClient) EXPECT() *MockMarketPricesEsiClientMockRecorder {
	return m.recorder
}

// GetMarketOrders mocks base method.
func (m *MockMarketPricesEsiClient) GetMarketOrders(arg0 context.Context, arg1 int64) ([]*client.MarketOrder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMarketOrders", arg0, arg1)
	ret0, _ := ret[0].([]*client.MarketOrder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMarketOrders indicates an expected call of GetMarketOrders.
func (mr *MockMarketPricesEsiClientMockRecorder) GetMarketOrders(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMarketOrders", reflect.TypeOf((*MockMarketPricesEsiClient)(nil).GetMarketOrders), arg0, arg1)
}
